### ISSUE TITLE
Could not connect to ProcExp device

### ISSUE THREAD

**Issue by bgospodaru** [Yaxser/Backstab#1]
Hi!
Any idea why this is happening?
![image](https://user-images.githubusercontent.com/12615581/122208076-8883ca80-ceab-11eb-99b0-c5b86d2fefa2.png)

Also, when dropping to a custom path, a new error appears:
![image](https://user-images.githubusercontent.com/12615581/122208201-afda9780-ceab-11eb-9464-ebfc7271e855.png)

I have compiled the project using the latest MSVC 16.10 on x64.

**Comment by Yaxser** [comment]
Hello Bogdan,

the error is because you are not running the CMD as admin. Error code 5 means ACCESS_DENIED

The error c0000033 refers to an invalid object name. NtloadDriver tries to read the driver reg key, which couldn't be written because you don't have sufficient privileges.

Can you please try again as admin? The purpose of the tool is to kill EDR after having the admin creds and not before.

**Comment by bgospodaru** [comment]
Hello,
Sorry for not mentioning it in the original thread, I am in fact running as administrator, that's why I can't figure out the problem.

**Comment by Yaxser** [comment]
I just pulled and rebuilt and I can't replicate. Also, I am positive that 5 refers to lack of privileges.

To debug this further, perhaps you can reach out to me at twitter and we start a live session to look at it together? I'll then update this issue with the findings

**Comment by bgospodaru** [comment]
Apparently having system privileges mitigates this error. To be honest I have no idea why local admin privileges are not enough on my VM, will try to figure it out.
For now, I'll close this issue. Thank you for your time!

**Comment by k4nfr3** [comment]
Hi, the issue is solved when you adjust your Token. Normally SeLoadDriverPrivilege should be enough, but It doesn't work for me. At the moment, if you want I can PR some code to get SeDebugPrivilege which then it works fine.
I also added to check if you are a mini check if you are running with privileges or not.
